#!/usr/bin/env python

import sys
import socket

class XRMClient:
    def __init__(self, host, port):
        self.sock = socket.socket()
        try:
            self.sock.connect((host, port))
        except socket.error as msg:
            print("    Failed to reach the XRM daemon.")
            print("    Please check the status of XRM daemon with following command:\n")
            print("    #systemctl status xrmd\n")
            self.sock.close()
            sys.exit(1)

    def send(self, jsonFile):
        jf = open(jsonFile, 'rb')
        data = jf.read()
        try:
            self.sock.sendall(data)
        except socket.error as msg:
            print("    Failed to send data to the XRM daemon.")
            print("    Please check the status of XRM daemon with following command:\n")
            print("    #systemctl status xrmd\n")
            self.sock.close()
            sys.exit(1)

    def receive(self, ):
        return self.sock.recv(131072)

    def close(self, ):
        self.sock.close()

if __name__ == "__main__":
    jsonFile = sys.argv[1]
    cli = XRMClient("localhost", 9763)
    cli.send(jsonFile)
    print(cli.receive())
    cli.close()
