#!/usr/bin/env python3

#
# Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
#

import sys
import platform
import socket
import json
from collections import OrderedDict

class XRMClient:
    def __init__(self, host, port):
        self.sock = socket.socket()
        try:
            self.sock.connect((host, port))
        except socket.error as msg:
            print("    Failed to reach the XRM daemon.")
            print("    Please check the status of XRM daemon with following command:\n")
            print("    #systemctl status xrmd\n")
            self.sock.close()
            sys.exit(1)

    def send(self, jsonFile):
        jf = open(jsonFile, 'rb')
        data = jf.read()
        try:
            self.sock.sendall(data)
        except socket.error as msg:
            print("    Failed to send data to the XRM daemon.")
            print("    Please check the status of XRM daemon with following command:\n")
            print("    #systemctl status xrmd\n")
            self.sock.close()
            sys.exit(1)

    def receive(self, ):
        total_data = bytearray()
        total_len = 0
        cur_len = 0
        while True:
            cur_data = self.sock.recv(131072)
            if cur_data:
                #print("recv len: " + str(len(cur_data)))
                if total_len == 0:
                    total_len = int.from_bytes(cur_data[0:4], byteorder='little')
                    cur_len = len(cur_data) - 4
                    total_data = bytearray(cur_data[4:])
                else:
                    cur_len += len(cur_data)
                    total_data += bytearray(cur_data)
                if cur_len >= total_len:
                    break
            else:
                break
        return bytes(total_data)

    def close(self, ):
        self.sock.close()

if __name__ == "__main__":
    if (sys.version_info[0] < 2) or ((sys.version_info[0] == 2) and (sys.version_info[1] < 7)):
        print("WARNING: Python version (" + platform.python_version() + ") is < 2.7. Please use newer version, otherwise may run into failure.")
    jsonFile = sys.argv[1]
    cli = XRMClient("localhost", 9763)
    cli.send(jsonFile)
    parsedOutput = json.loads(cli.receive(), object_pairs_hook = OrderedDict)
    print(json.dumps(parsedOutput, indent = 4, sort_keys = False))
    cli.close()
